---
version: "3.9"

services:
  27python:
    build:
      context: .
      args:
        PYTHON_VERSION: "2.7"

  38python:
    build:
      context: .
      args:
        PYTHON_VERSION: "3.8"

  39python:
    build:
      context: .
      args:
        PYTHON_VERSION: "3.9"

  310python:
    build:
      context: .
      args:
        PYTHON_VERSION: "3.10"

  311python:
    build:
      context: .
      args:
        PYTHON_VERSION: "3.11"

  38python211:
    build:
      context: .
      dockerfile: Dockerfile.with-ansible-version
      args:
        PYTHON_VERSION: "3.8"
        ANSIBLE_VERSION: "2.11.12"
