---
- name: Test CICS Collection
  collections:
    - ibm.ibm_zos_cics
  hosts: "localhost"

  tasks:
    - name: Get program definitions
      ibm.ibm_zos_cics.cmci_get:
        cmci_host:
        cmci_port:
        cmci_user:
        cmci_password:
        context:
        scope:
        scheme: http
        type: CICSDefinitionProgram
        resources:
          filter:
            name: TWYD*
          get_parameters:
            - name: csdgroup
              value: TWYDCSD1
        fail_on_nodata: false
      register: result

    - debug:
        msg: "{{ result }}"
